title: SmartTube (Official Site)
description: Free premium app for Android boxes and tvs
remote_theme: pages-themes/cayman@v0.2.0
plugins_dir:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: jekyll-theme-cayman